### ISSUE TITLE
Remove public constructor requirement

### ISSUE THREAD

**Issue by justinjstark** [mattnischan/Immutable.Net#1]
I was playing around and quickly ran into the caveat in the readme:

> Data types that are wrapped using Immutable and ImmutableBuilder must have parameterless constructors. This may change in the future.

Not only must they have a parameterless constructor, the constructor must be public.

Without this limitation, I can do something like this:

``` c#
public class Customer
{
  public string Name { get; set; }
  public Immutable<Address> Address { get; set; }

  private Customer()
  {
  }

  public static Immutable<Customer> Create(string name, Immutable<Address> address)
  {
    return Immutable<Customer>.Create(new Customer { Name = name, Address = address });
  }
}
```

Purely encapsulated immutable glory.

**Comment by mattnischan** [comment]
@justinjstark Thanks for the PR! Closing this as it has been merged.
