### ISSUE TITLE
ImmutableJsonConverter not caching Factories/Accessors properly

### ISSUE THREAD

**Issue by L0w3nd** [mattnischan/Immutable.Net#14]
ImmutableJsonConverter ReadJson and WriteJson both use the wrong GetOrAdd() override resulting in BuildFactory() and BuildAccessor() getting called everytime we try to get values from the cache, even if it is already cached.

I haven't tested the fix yet, but this appears to be causing a performance issue while serializing a larger collection of items to a single JSON string.

**Comment by mattnischan** [comment]
Issued addressed with #15.

**Comment by L0w3nd** [comment]
The results were better than expected. For my particular scenario which hit this bug repeatedly I saw total run time drop from ~7.5 minutes to ~2.75 minutes.
