### ISSUE TITLE
Data received by Get() can be used to mutate .. everything

### ISSUE THREAD

**Issue by quetzalcoatl** [mattnischan/Immutable.Net#17]
Taking the front-page example:

```
public class Order
{
  public int OrderId { get; set; }
  public string CustomerName { get; set; }
  public string Description { get; set; }
}

var order = Immutable.Create(new Order 
{
    OrderId = 7,
    CustomerName = "Bobby Sandwich",
    Description = "Ordered a meatball sub."
});
```

we can now easily get the whole contents and play with it, because, well, why not:
```
var hmWhatDoIHaveHere= order.Get(o => o);
hmWhatDoIHaveHere.CustomerName = "Sobby Bandwich";
```

and it affects the immutable:
```
var str = order.Get(o => o.CustomerName);
Console.WriteLine(str); // writes out "Sobby Bandwich"
```

It turns out that `hmWhatDoIHaveHere` is actually the real inner object that the immutable holds.. I was totally expecting that `Get` returns a copy for non-primitives, or some kind of dynamic proxy filtering setters, or some other trick, but .. nothing. Get just directly returns the inner object `_self` in this case.

**It's actually a huge issue and it should at least be noted in the library description.**

Sidenote - Another thing is, if the library does not aim to provide 100% immutability, then .. what do we need the 'Immutable' class at all for? The .Modify or .ToBuilder could simply be extension methods on type <T> and it'd be not a bit less functional and it'd be easier to use and apply to existing code (no more pasting Immutable<> everywhere).

**Comment by mattnischan** [comment]
The intention is to provide 100% immutability (with this caveat that you have noticed). It would not make sense at all to make them extension methods as that would provide no indication of intention or protect the inner instance.  Additionally the ToBuilder extension would be fairly useless (an object is already mutable).

It was actually not possible to return yourself in earlier versions of Immutable.Net, you would get an exception at runtime. However, when the library moved from using Expressions to simple Actions (enormous performance increase and allocations decrease), it became impossible to inspect the lambda being passed in for this specific case. Additionally, there were some users who didn't care for the fact that there was no way of making it a compile time error, and others who liked being able to access the inner instance easily to use normal getters without the performance hit of cloing the inner instance.

You are right that this should be indicated in the readme, and I apologize for that. I actually thought it was.

I think I have an easy way I just thought of of cloning the inner instance in this case, which I can add to the next version of Immutable.Net. If you have ideas, I'm always open to PRs.

**Comment by quetzalcoatl** [comment]
> (...) Additionally the ToBuilder extension would be fairly useless

No, no, you got me wrong. My point of view was, "if 100% immutability is not achievable/impossible/notagoal/etc, then exposing this Modify/ToBuilder as extension methods would simplify the usage." I know that the object is already mutable, but we're not going away from the intent of not mutating the source. I/We still want it, but if we accept that the lib cannot guarantee it, then we/developers have to take care of it ourselves, alright, we can live with it. However, if the objects are mutable anyways, and if we have to be careful, then we still want an easy way to clone&update them. Modify would still be useful as it would allow to easily clone&change the object, and ToBuilder would still be useful as it would still allow to clone&change&change&change enmasse without intermediate clones..

You've said that without Immutable<> wrapper the immutability-intent would be being lost when it's all just extension methods - that's true, I understand that. I won't argue with that, having a clear contract is also an important aspect, especially if the inner object(s) are easy to be accidentaly modified (as we see it now). To me however, it's on par with the "unwieldiness" of marking everything with extra generic wrapper.. but that's a matter of personal preferences I think.

> I think I have an easy way I just thought of of cloning the inner instance in this case
Regarding that, I also immediately thought about it, but then.. I have mixed feelings for this. If a quick shallow copy is returned, then we're avoiding from modification at the root object, but any inner objects (Person.Address, etc) can be mutated anyways so it's kind of pointless..

Then, deep-copying is probably something we'd like to avoid implementing, with potential cycles in object graph and other problems, unless some kind of https://github.com/force-net/DeepCloner is used for that..

Then2, if we do shallow or deep copy in the Get() itself, then each call to Get() might return a new copy, not cool.. memoize it, maybe? that in turn protectes the source, but causes any changes will propagate to other callers to Get(), so it's even less cool..

Then3, delegates-vs-expressions, exactly, but how to detect the case of Get(x=>x) if it's a delegate? we can't inspect it, so there are only two options: either depend on the fact it's Func<T1,T2> with T1==T2, which is somewhat risky, what if we have a classic tree or linked list where each node is of the same type.. or we can call the func and compare if the func returned the same source object.. that probably would do the trick, but it'd be rather inobvious if Get(x=>x) returned a clone, but Get(x=>x.y) wouldn't.. 

The only two things I can think of is either returning a deep-recursive dynamic proxy that blocks setters, or deep-cloning, the former somewhat heavy and not easy to implement (unless another lib is pulled), the latter a bit easier and even heavier than the former.. hm.. okay, another way could be requiring classes to not have setters and getting back to expressions instead of runnable delegates with setters.. like in https://github.com/AutoReviser/AutoReviser, but as you've said, you've just moved away from a similar mechanism..

Sorry for this rambling, but I'm out of ideas except for documenting the current behavior.

**Comment by mattnischan** [comment]
I think the deep-clone issue is somewhat endemic to the problem space, really. If your immutable object contains within itself mutable objects, you're always going to be able to get yourself into trouble:

```csharp
public class NameDetails
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

public class Person
{
    public NameDetails Name { get; set; }
}

var person = Immutable.Create(new Person());
person = person.Modify(p => p.Name = Immutable.Create(new NameDetails { FirstName = "Bob", LastName = "Smith" }));

var name = person.Get(p => p.Name);
name.LastName = "Smyth";

Console.WriteLine(person.Get(p => p.Name.LastName)); //Prints "Smyth", oops
```

We can't really protect against that unless we also do deep-clone on any `Get()` call, which would be unacceptably expensive. If one wants safety even in a nested object scenario, one really needs to do this:

```csharp
public class NameDetails
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

public class Person
{
    public Immutable<NameDetails> Name { get; set; }
}

var person = Immutable.Create(new Person());
person = person.Modify(p => p.Name = new NameDetails { FirstName = "Bob", LastName = "Smith" });

var name = person.Get(p => p.Name);
name.LastName = "Smyth"; //Compiler error, type of Immutable<NameDetails> doesn't have a LastName field

person = person.Modify(p => p.Name = p.Name.Modify(n => n.LastName = "Smyth")); //Now we did it safely
```

The syntax isn't the most fantastic, but that does get you there.

Given that it's a problem anyhow with 'mutable inside immutable', I feel like it's safe to return a shallow copy of the `_self` enclosed instance on Get, and make it clear in the method summary that this will return a copy in that case. However, I'm open to other opinions.

**Comment by mattnischan** [comment]
Since there hasn't really been more activity here, I've merged the PR with the solution described and I'll go ahead and close this issue out.
