### ISSUE TITLE
Any suggestions on implementing this with Unity?

### ISSUE THREAD

**Issue by austinmao** [mattnischan/Immutable.Net#6]
Hello, I'm trying to implement this with Unity for https://github.com/austinmao/reduxity/

Unfortunately, Unity does not support `System.Collections.Concurrent`. Is there any way to get this to work?

**Comment by justinjstark** [comment]
Unfortunately, this project only supports >= .NET 4.0.

`System.Collections.Concurrent` is used for the delegate cache. You could fork this project and use a regular collection. But, if your application is highly concurrent, you'll want to implement your own concurrent dictionary with locks as generating the delegates is expensive.

**Comment by austinmao** [comment]
I really, really appreciate your help! I was able to build a version of System.Collections.Concurrent that works for .NET 3.5 for unity. Now, the issue that is blocking me is System.Expressions.Assign and .Block. Do you have any substitutes for these or other suggestions?

**Comment by mattnischan** [comment]
That's going to be a little more difficult. The .Net 3.5 version of expressions is not nearly as robust. Expression.Assign in particular is not available, although there are a couple of workarounds floating around on StackOverflow regarding that. You may have to emit a method with IL directly if you want the full gamut of functionality.

**Comment by austinmao** [comment]
I'm fairly new to C# and trying to port react-redux to Unity as a convenient framework for web and mobile developers who are familiar with the pattern to have an easier way of getting into VR (see [Reduxity](https://github.com/austinmao/reduxity/) ).

Immutability is one of the final remaining puzzles. Given that I'm quite new, can you give me any more specifics in pointing me in the right direction? What functionality will be lost if Assign and Block are not used? What would I replace them with?

Thanks again. You are awesome!

**Comment by mattnischan** [comment]
Hey there, sorry I wasn't able to help you at the time, but Unity now supports .Net 4.6!

I'm going to close this since it is compatible now.
